# Generated by Django 5.1.7 on 2025-03-22 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.era')),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientists', to='api.era')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalEvent',
        ),
        migrations.AddField(
            model_name='event',
            name='scientists',
            field=models.ManyToManyField(related_name='events', to='api.scientist'),
        ),
    ]
