# Generated by Django 4.2.20 on 2025-04-05 02:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_era_event_scientist_delete_historicalevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用戶ID')),
                ('message', models.TextField(default='', verbose_name='訊息')),
                ('is_from_user', models.BooleanField(default=True, verbose_name='是否來自用戶')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '對話歷史',
                'verbose_name_plural': '對話歷史',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chemist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未命名化學家', max_length=100, verbose_name='姓名')),
                ('birth_year', models.IntegerField(default=0, verbose_name='出生年份')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='逝世年份')),
                ('bio', models.TextField(blank=True, verbose_name='簡介')),
                ('portrait_path', models.CharField(blank=True, max_length=255, verbose_name='肖像路徑')),
                ('model_path', models.CharField(blank=True, max_length=255, verbose_name='模型路徑')),
                ('position_x', models.FloatField(default=0, verbose_name='位置X')),
                ('position_y', models.FloatField(default=0, verbose_name='位置Y')),
                ('position_z', models.FloatField(default=0, verbose_name='位置Z')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '化學家',
                'verbose_name_plural': '化學家',
                'ordering': ['birth_year'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名事件', max_length=200, verbose_name='標題')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('year', models.IntegerField(default=0, verbose_name='年份')),
                ('importance_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='重要程度')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('chemist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.chemist', verbose_name='相關化學家')),
            ],
            options={
                'verbose_name': '歷史事件',
                'verbose_name_plural': '歷史事件',
                'ordering': ['year'],
            },
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='era',
        ),
        migrations.AlterModelOptions(
            name='era',
            options={'ordering': ['year'], 'verbose_name': '時代', 'verbose_name_plural': '時代'},
        ),
        migrations.RemoveField(
            model_name='era',
            name='title',
        ),
        migrations.AddField(
            model_name='era',
            name='camera_position_x',
            field=models.FloatField(default=10, verbose_name='相機位置X'),
        ),
        migrations.AddField(
            model_name='era',
            name='camera_position_y',
            field=models.FloatField(default=5, verbose_name='相機位置Y'),
        ),
        migrations.AddField(
            model_name='era',
            name='camera_position_z',
            field=models.FloatField(default=10, verbose_name='相機位置Z'),
        ),
        migrations.AddField(
            model_name='era',
            name='camera_target_x',
            field=models.FloatField(default=0, verbose_name='相機目標X'),
        ),
        migrations.AddField(
            model_name='era',
            name='camera_target_y',
            field=models.FloatField(default=0, verbose_name='相機目標Y'),
        ),
        migrations.AddField(
            model_name='era',
            name='camera_target_z',
            field=models.FloatField(default=0, verbose_name='相機目標Z'),
        ),
        migrations.AddField(
            model_name='era',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間'),
        ),
        migrations.AddField(
            model_name='era',
            name='name',
            field=models.CharField(default='未命名時代', max_length=100, verbose_name='時代名稱'),
        ),
        migrations.AddField(
            model_name='era',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='era',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='era',
            name='year',
            field=models.IntegerField(default=0, verbose_name='年份'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Scientist',
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='era',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.era', verbose_name='所屬時代'),
        ),
        migrations.AddField(
            model_name='chemist',
            name='era',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemists', to='api.era', verbose_name='所屬時代'),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='chemist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='api.chemist', verbose_name='化學家'),
        ),
        migrations.AddIndex(
            model_name='historicalevent',
            index=models.Index(fields=['year'], name='api_histori_year_e902b0_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalevent',
            index=models.Index(fields=['era'], name='api_histori_era_id_623f08_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalevent',
            index=models.Index(fields=['chemist'], name='api_histori_chemist_c8daf8_idx'),
        ),
        migrations.AddIndex(
            model_name='chemist',
            index=models.Index(fields=['era'], name='api_chemist_era_id_2df2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='chemist',
            index=models.Index(fields=['birth_year'], name='api_chemist_birth_y_2ab019_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['chemist'], name='api_chathis_chemist_4a77bb_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['created_at'], name='api_chathis_created_247dd1_idx'),
        ),
    ]
