# Generated by Django 4.2.11 on 2025-05-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_chathistory_chemist_historicalevent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="era",
            options={
                "ordering": ["start_year"],
                "verbose_name": "時代",
                "verbose_name_plural": "時代",
            },
        ),
        migrations.RemoveField(
            model_name="era",
            name="year",
        ),
        migrations.AddField(
            model_name="era",
            name="end_year",
            field=models.IntegerField(default=0, verbose_name="結束年份"),
        ),
        migrations.AddField(
            model_name="era",
            name="model_path",
            field=models.CharField(blank=True, max_length=255, verbose_name="模型路徑"),
        ),
        migrations.AddField(
            model_name="era",
            name="start_year",
            field=models.IntegerField(default=0, verbose_name="開始年份"),
        ),
    ]
