# Generated by Django 4.2.11 on 2025-05-29 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_era_options_remove_era_year_era_end_year_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chathistory",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "聊天記錄",
                "verbose_name_plural": "聊天記錄",
            },
        ),
        migrations.AlterModelOptions(
            name="chemist",
            options={"verbose_name": "化學家", "verbose_name_plural": "化學家"},
        ),
        migrations.AlterModelOptions(
            name="era",
            options={
                "ordering": ["year"],
                "verbose_name": "時代",
                "verbose_name_plural": "時代",
            },
        ),
        migrations.RemoveIndex(
            model_name="chathistory",
            name="api_chathis_chemist_4a77bb_idx",
        ),
        migrations.RemoveIndex(
            model_name="chathistory",
            name="api_chathis_created_247dd1_idx",
        ),
        migrations.RemoveIndex(
            model_name="chemist",
            name="api_chemist_era_id_2df2d1_idx",
        ),
        migrations.RemoveIndex(
            model_name="chemist",
            name="api_chemist_birth_y_2ab019_idx",
        ),
        migrations.RemoveIndex(
            model_name="historicalevent",
            name="api_histori_year_e902b0_idx",
        ),
        migrations.RemoveIndex(
            model_name="historicalevent",
            name="api_histori_era_id_623f08_idx",
        ),
        migrations.RemoveIndex(
            model_name="historicalevent",
            name="api_histori_chemist_c8daf8_idx",
        ),
        migrations.RemoveField(
            model_name="chathistory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="chathistory",
            name="is_from_user",
        ),
        migrations.RemoveField(
            model_name="chathistory",
            name="message",
        ),
        migrations.RemoveField(
            model_name="chathistory",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="chemist",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="era",
            name="camera_position_x",
        ),
        migrations.RemoveField(
            model_name="era",
            name="camera_position_y",
        ),
        migrations.RemoveField(
            model_name="era",
            name="camera_position_z",
        ),
        migrations.RemoveField(
            model_name="era",
            name="camera_target_x",
        ),
        migrations.RemoveField(
            model_name="era",
            name="camera_target_y",
        ),
        migrations.RemoveField(
            model_name="era",
            name="camera_target_z",
        ),
        migrations.RemoveField(
            model_name="era",
            name="end_year",
        ),
        migrations.RemoveField(
            model_name="era",
            name="model_path",
        ),
        migrations.RemoveField(
            model_name="era",
            name="start_year",
        ),
        migrations.RemoveField(
            model_name="historicalevent",
            name="era",
        ),
        migrations.RemoveField(
            model_name="historicalevent",
            name="importance_level",
        ),
        migrations.AddField(
            model_name="chathistory",
            name="content",
            field=models.TextField(default="", verbose_name="內容"),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="role",
            field=models.CharField(default="", max_length=50, verbose_name="角色"),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="時間戳"
            ),
        ),
        migrations.AddField(
            model_name="chemist",
            name="description",
            field=models.TextField(default="", verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="era",
            name="model_url",
            field=models.URLField(blank=True, default="", verbose_name="3D 模型 URL"),
        ),
        migrations.AddField(
            model_name="era",
            name="soundtrack_url",
            field=models.URLField(blank=True, default="", verbose_name="背景音效 URL"),
        ),
        migrations.AddField(
            model_name="era",
            name="year",
            field=models.IntegerField(default=0, verbose_name="年份"),
        ),
        migrations.AddField(
            model_name="historicalevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("discovery", "重要發現"),
                    ("invention", "重要發明"),
                    ("publication", "重要著作"),
                    ("award", "重要獎項"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=50,
                verbose_name="事件類型",
            ),
        ),
        migrations.AddField(
            model_name="historicalevent",
            name="image_path",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="事件圖片路徑",
            ),
        ),
        migrations.AlterField(
            model_name="chemist",
            name="birth_year",
            field=models.IntegerField(default=1800, verbose_name="出生年份"),
        ),
        migrations.AlterField(
            model_name="chemist",
            name="death_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="死亡年份"),
        ),
        migrations.AlterField(
            model_name="chemist",
            name="era",
            field=models.IntegerField(default=0, verbose_name="時代"),
        ),
        migrations.AlterField(
            model_name="chemist",
            name="model_path",
            field=models.CharField(
                default="", max_length=200, verbose_name="3D模型路徑"
            ),
        ),
        migrations.AlterField(
            model_name="chemist",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="chemist",
            name="portrait_path",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="肖像路徑",
            ),
        ),
        migrations.AlterField(
            model_name="chemist",
            name="position_x",
            field=models.FloatField(default=0, verbose_name="X座標"),
        ),
        migrations.AlterField(
            model_name="chemist",
            name="position_y",
            field=models.FloatField(default=0, verbose_name="Y座標"),
        ),
        migrations.AlterField(
            model_name="chemist",
            name="position_z",
            field=models.FloatField(default=0, verbose_name="Z座標"),
        ),
        migrations.AlterField(
            model_name="chemist",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="更新時間"
            ),
        ),
        migrations.AlterField(
            model_name="era",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="era",
            name="description",
            field=models.TextField(default="", verbose_name="時代描述"),
        ),
        migrations.AlterField(
            model_name="era",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="時代名稱"),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="description",
            field=models.TextField(default="", verbose_name="事件描述"),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="title",
            field=models.CharField(default="", max_length=200, verbose_name="事件標題"),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="year",
            field=models.IntegerField(default=0, verbose_name="發生年份"),
        ),
    ]
