# Generated by Django 4.2.11 on 2025-04-06 04:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chemist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("era", models.IntegerField(verbose_name="時代")),
                ("description", models.TextField(verbose_name="描述")),
                ("position_x", models.FloatField(default=0, verbose_name="X座標")),
                ("position_y", models.FloatField(default=0, verbose_name="Y座標")),
                ("position_z", models.FloatField(default=0, verbose_name="Z座標")),
                (
                    "model_path",
                    models.CharField(max_length=200, verbose_name="3D模型路徑"),
                ),
                (
                    "birth_year",
                    models.IntegerField(default=1800, verbose_name="出生年份"),
                ),
                (
                    "death_year",
                    models.IntegerField(blank=True, null=True, verbose_name="死亡年份"),
                ),
                (
                    "portrait_path",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="肖像路徑"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "化學家",
                "verbose_name_plural": "化學家",
            },
        ),
        migrations.CreateModel(
            name="HistoricalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="事件標題")),
                ("description", models.TextField(verbose_name="事件描述")),
                ("year", models.IntegerField(verbose_name="發生年份")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("discovery", "重要發現"),
                            ("invention", "重要發明"),
                            ("publication", "重要著作"),
                            ("award", "重要獎項"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="事件類型",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="事件圖片路徑",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "chemist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="chemists.chemist",
                        verbose_name="相關化學家",
                    ),
                ),
            ],
            options={
                "verbose_name": "歷史事件",
                "verbose_name_plural": "歷史事件",
                "ordering": ["year"],
            },
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50, verbose_name="角色")),
                ("content", models.TextField(verbose_name="內容")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間戳"
                    ),
                ),
                (
                    "chemist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_history",
                        to="chemists.chemist",
                        verbose_name="化學家",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天記錄",
                "verbose_name_plural": "聊天記錄",
                "ordering": ["timestamp"],
            },
        ),
    ]
