# Generated by Django 4.2.20 on 2025-04-05 02:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('era', models.CharField(max_length=50, verbose_name='時代')),
                ('description', models.TextField(verbose_name='描述')),
                ('position_x', models.FloatField(default=0, verbose_name='X座標')),
                ('position_y', models.FloatField(default=0, verbose_name='Y座標')),
                ('position_z', models.FloatField(default=0, verbose_name='Z座標')),
                ('model_path', models.CharField(max_length=200, verbose_name='3D模型路徑')),
            ],
            options={
                'verbose_name': '化學家',
                'verbose_name_plural': '化學家',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='角色')),
                ('content', models.TextField(verbose_name='內容')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間戳')),
                ('chemist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='chemists.chemist', verbose_name='化學家')),
            ],
            options={
                'verbose_name': '聊天記錄',
                'verbose_name_plural': '聊天記錄',
                'ordering': ['timestamp'],
            },
        ),
    ]
