# Generated by Django 4.2.20 on 2025-04-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemist',
            name='birth_year',
            field=models.IntegerField(default=1800, verbose_name='出生年份'),
        ),
        migrations.AddField(
            model_name='chemist',
            name='death_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='死亡年份'),
        ),
        migrations.AddField(
            model_name='chemist',
            name='portrait_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='肖像路徑'),
        ),
        migrations.AlterField(
            model_name='chemist',
            name='era',
            field=models.IntegerField(verbose_name='時代'),
        ),
    ]
