# Generated by Django 4.2.20 on 2025-04-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemists', '0002_chemist_birth_year_chemist_death_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='事件標題')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('year', models.IntegerField(verbose_name='發生年份')),
                ('event_type', models.CharField(choices=[('discovery', '重要發現'), ('invention', '重要發明'), ('publication', '重要著作'), ('award', '重要獎項'), ('other', '其他')], max_length=50, verbose_name='事件類型')),
                ('image_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='事件圖片路徑')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('chemist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chemists.chemist', verbose_name='相關化學家')),
            ],
            options={
                'verbose_name': '歷史事件',
                'verbose_name_plural': '歷史事件',
                'ordering': ['year'],
            },
        ),
    ]
