# Generated by Django 4.2.11 on 2025-04-06 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chemists", "0003_historicalevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemist",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="創建時間"
            ),
        ),
        migrations.AddField(
            model_name="chemist",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="更新時間"
            ),
        ),
    ]
