version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - chronochem-network
    ports:
      - "8001:8001"

  celery:
    build:
      context: ./backend
      dockerfile: ../docker/backend/celery.Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - redis
    networks:
      - chronochem-network

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/var/lib/postgresql/backups
    environment:
      - POSTGRES_DB=chronochem
      - POSTGRES_USER=chronochem
      - POSTGRES_PASSWORD=chronochem
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chronochem -d chronochem"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - chronochem-network
    ports:
      - "6379:6379"
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - static_volume:/usr/share/nginx/static
      - media_volume:/usr/share/nginx/media
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - chronochem-network
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  chronochem-network:
    driver: bridge