version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: chrono_backend
    restart: always
    env_file:
      - ../docker/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ../backend:/app
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: chrono_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app

  db:
    image: postgres:15
    container_name: chrono_db
    restart: always
    env_file:
      - ../docker/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: chrono_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: