name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 165.22.101.120 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh root@165.22.101.120 'cd /root/chrono-chem && \
            git pull origin main && \
            docker-compose down && \
            docker-compose build && \
            docker-compose up -d'

      - name: Verify deployment
        run: |
          ssh root@165.22.101.120 'cd /root/chrono-chem && \
            docker-compose ps && \
            curl -k -I https://chronochem.uno' 